### ISSUE TITLE
uupdump windows outdated EMPTY_FILELIST

### ISSUE THREAD

**Issue by asyba** [utmapp/docs.getutm.app#17]
https://uupdump.net/

If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.

```
Resultados de la descarga:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a92d91|OK  |   7.0KiB/s|/Users/federicobechini/Documents/Windows UTM virtual/21390.2025_arm64_en-us_multi_7811e991_convert/aria2_script.5606.txt

Leyenda:
(OK):descarga completada.
Unable to retrieve data from Windows Update servers. Reason: EMPTY_FILELIST
If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.
```

How I can install Windows 10 if all dump files are not anymore?

**Comment by philippjbauer** [comment]
I'm experiencing the same issue trying to download WIN 10 ARM64.
Is there an alternative, maybe an ISO file to download?

**Comment by osy** [comment]
We now recommend using CrystalFetch: https://docs.getutm.app/guides/windows/
