### ISSUE TITLE
virtiofs supported?

### ISSUE THREAD

**Issue by gkyildirim** [utmapp/docs.getutm.app#4]
https://github.com/utmapp/docs.getutm.app/blob/main/guest-support/sharing/directory.md indicates that VirtofFs is supported.
I guess virtiofs is not supported by UTM at the moment (https://github.com/utmapp/UTM/issues/4386).
Should the docs updated accordingly?

**Comment by osy** [comment]
Not sure what the question is. Virtiofs is supported in apple backend vms

**Comment by fredleger** [comment]
i guess this one should be reopened.
the question was about updating the docs if virtiofs is supported (but i admit the title is not ideal)

For now it seems we shoudl do : `mount -t 9p -o trans=virtio share {mount point] -oversion=9p2000.L`
But the docs mentions : `sudo mount -t virtiofs share [mount point]`
